name: "Build Android APK"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export:
    name: Export Android APK
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Export Directory
        run: mkdir -v -p build

      - name: Build Android APK
        run: |
          godot --headless --export-debug "Android" build/PentagonKingdoms.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PentagonKingdoms-APK
          path: build/PentagonKingdoms.apk
          
